version: '3.9'

services:

  nginx:
    image: nginx
    hostname: nginx
    container_name: nginx
    restart: unless-stopped
    ports:
      - 8080:80
      - 8081:443
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ./places_app:/var/www/

  php:
      build:
        context: ./php
      hostname: php
      container_name: php
      restart: unless-stopped
      user: root
      working_dir: /var/www/
      volumes:
        - ./places_app:/var/www
      depends_on:
        - db

  db:
    image: postgres
    hostname: db
    container_name: db
    restart: unless-stopped
    environment:
      POSTGRES_DB: "places"
      POSTGRES_USER: "admin"
      POSTGRES_PASSWORD: "admin"
      PGDATA: "/var/lib/postgresql/data/pgdata"
    ports:
      - 5432:5432
    volumes:
      - ./db_data:/var/lib/postgresql/data/pgdata


networks:
  default:
    driver: bridge
    driver_opts:
      com.docker.network.driver.mtu: 1450